### ISSUE TITLE
Use proper naming convention across project

### ISSUE THREAD

**Issue by apexkid** [SaptakS/opinator#10]
Convention layout

File name: all small letters no special characters.
Modules: CamelCase
Classes: cClassname
Private variables: mVariable

@rahulrrixe append these details.

**Comment by vivekanand1101** [comment]
I have  implemented the naming conventions except Classes and Private variables.

**Comment by apexkid** [comment]
https://www.python.org/dev/peps/pep-0008/

I think we can follow this.

**Comment by fluffybeing** [comment]
@apexkid PEP8 guideline would be best. install `anaconda` or `PEP8` packages in sublime. It will make easy for you to implement the guideline.

**Comment by apexkid** [comment]
@vivekanand1101 Status on this?

**Comment by vivekanand1101** [comment]
PEP8 followed and will be followed in future.
