### ISSUE TITLE
Integrate sentiment analysis code

### ISSUE THREAD

**Issue by apexkid** [SaptakS/opinator#11]
Validate the python wrappers and if they do not suit the purpose then use CoreNLP directly and modify the I/O.
Please note: Do not add CoreNLP package into git. Write it as a dependency in documentation clearly with proper path. Its is over 300MB and should not be included in git.

**Comment by SaptakS** [comment]
ok. I will do it asap. Need to make a few changes in the python wrapper.

**Comment by apexkid** [comment]
@SaptakS Status on this?

**Comment by SaptakS** [comment]
Integrated. Please check once @apexkid
