### ISSUE TITLE
Store Sentiment scores in DB

### ISSUE THREAD

**Issue by apexkid** [SaptakS/opinator#17]
To prevent re-calculating of SS on each hit, we will store <SS, Detail-page> mapping in DB with the timestamp on when it was recorded. A config value X will decide when to expire the SS and recalculate.

**Comment by apexkid** [comment]
DB to wrapped with sql-alchemy.

**Comment by vivekanand1101** [comment]
@apexkid  leave this to me

**Comment by vivekanand1101** [comment]
@apexkid @rahulrixxe Please verify the code (db-enhancement branch). I have tested it once. Readme is there.

**Comment by vivekanand1101** [comment]
@apexkid please verify the code (db-enhancement branch) . I have tested it once. Readme is there.

**Comment by vivekanand1101** [comment]
Done
