### ISSUE TITLE
Test refactor branch code.

### ISSUE THREAD

**Issue by apexkid** [SaptakS/opinator#5]
I made changes to name and folder in refactor branch. This would have caused breaking of multiple files in code. Please make appropriate changes. 

Do a diff of refactor and master branch to know the changes.
http://stackoverflow.com/questions/822811/showing-which-files-have-changed-between-git-branches

**Comment by SaptakS** [comment]
Sir, I have merged the refactor branch and made appropriate changes. Please see the repo once to confirm.
