### ISSUE TITLE
Remove venv source code from your project.

### ISSUE THREAD

**Issue by fluffybeing** [SaptakS/opinator#7]
Why is venv folder is lying in the project repo?

**Comment by apexkid** [comment]
High priority. Please do ASAP.

**Comment by SaptakS** [comment]
venv folder removed.

**Comment by vivekanand1101** [comment]
I have installed virtualenvwrapper but i still had to use pip freeze > requirements.txt. I couldn't find any other method. I think it works fine with virtualenvwrapper.

**Comment by apexkid** [comment]
Verified.
